### ISSUE TITLE
Load More button still shows when user is at the end of a (Events) list

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#100]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary

1. Clicking the Load More button until all events have been loaded still shows the button
1. OS/Browser, OSX / Chrome (latest of each)
1. Environment: stage / prod
1. Exact steps to reproduce (example below)
      1. Click Load More button in Upcoming Events List 
      1. When at the end of the list, the Load More button is still showing
1. Expected result: The Load More button should hide when at the end of list
1. Actual result: The Load More button shows and clicking it does nothing
1. Error message (if applicable)
1. screenshot(jpg) or video(gif) if any
<img width="1204" alt="screen shot 2017-12-03 at 8 37 15 pm" src="https://user-images.githubusercontent.com/895923/33532749-5de41770-d86a-11e7-9d31-4012ab7a19ad.png">

**Comment by thescientist13** [comment]
looks like working on #99 could help fix this.

**Comment by thescientist13** [comment]
is resolved by https://github.com/ProvidenceGeeks/website-frontend/pull/101

**Comment by saimatsumoto** [comment]
Load More button no longer shows at the very end of events list content; moving to DONE.
![load more button](https://user-images.githubusercontent.com/25797778/33619219-9acbe390-d9b2-11e7-9092-218bbafb51b2.png)
