### ISSUE TITLE
Post List card heading is not styled correctly

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#102]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary

1. As a compromise in ( #80 ) it was agreed that the styling of the posts heading would be amenable by the team 
1. OS/Browser: all
1. Environment: stage
1. Exact steps to reproduce (example below)
      1. Land on the Home Page
      1. Click on Posts
1. Expected result: It should look like in the application design (see below)
1. Actual result: It is not styled like in the application design (see below)
1. Error message (if applicable): N / A

**Expected**
<img width="303" alt="screen shot 2017-12-04 at 11 00 15 am" src="https://user-images.githubusercontent.com/895923/33562131-6c412c40-d8e2-11e7-9228-3bfa171881ad.png">

**Actual**
<img width="404" alt="screen shot 2017-12-04 at 9 55 27 am" src="https://user-images.githubusercontent.com/895923/33562135-7258b256-d8e2-11e7-9a85-96509e4d839e.png">

<img width="461" alt="screen shot 2017-12-04 at 11 50 56 am" src="https://user-images.githubusercontent.com/895923/33564810-739cdbe0-d8e9-11e7-8b9e-7b5ef1b6410a.png">

My recommendation would be to target the `Card` component's styles and override them from the `BlogPostsList` component's `.scss`

**Comment by thescientist13** [comment]
My recommendation would be to target the `Card` component's styles and override them from the `BlogPostsList` component's _.scss_

**Comment by saimatsumoto** [comment]
@thescientist13 @mdiwale 
Regarding the author/date font issue that was raised yesterday, is there a need for a defect issue? 
![blog-post card_author font](https://user-images.githubusercontent.com/25797778/34277238-e3f49da6-e672-11e7-8247-63e514774fa5.png)

device/OS: 
Galaxy S5 / Chrome v53.0.2785.124
iPhone5c / Safari v10.0
Windows10/Chrome v62.0.3202.94 emulator

**Comment by thescientist13** [comment]
@saimatsumoto 
Ah yes, I see a couple things there.  I would just re-open this issue, and just numerically list out what the specific gaps are for @mdiwale

**Comment by saimatsumoto** [comment]
@mdiwale CC: @thescientist13 
1. Blog title should be left aligned
2. Author/Date font should be Josefin Sans Regular as per [styleguide]
(https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design#styleguide).

**Comment by thescientist13** [comment]
@saimatsumoto 
The color of the font should be gray too, no?

**Comment by saimatsumoto** [comment]
yes it should be gray but also, it looks like it's already set up (unless I'm looking at the wrong css/style.
<img width="954" alt="author color" src="https://user-images.githubusercontent.com/25797778/34682452-fa5e5070-f46c-11e7-8879-1b87ed7968eb.png">

**Comment by thescientist13** [comment]
Sounds good.  In the designs it looked darker gray, but if you are confirming that this is the correct color from the styleguide we should be using, then all good by me 👍 

Thanks for double checking!

**Comment by saimatsumoto** [comment]
- [x] TEST in stage: displayed as expected.
1. Blog title should be left aligned
2. Author/Date font should be Josefin Sans Regular as per styleguide.
<img src="https://user-images.githubusercontent.com/25797778/34727327-95f057d8-f524-11e7-829f-574793bd6af7.png" width="30%" height="30%">

device/OS: 
Galaxy J7 Prime / Android 7.0 / Chrome v60.0.3112.116
Windows10/Chrome v63.0.3239.84 emulator 

- [ ] TEST in prod: pending
