### ISSUE TITLE
Blog Posts images do not load until page is scrolled

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-frontend#111]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary

1. After toggling to blog posts view on the homepage, blog images do not load until the user scrolls down the page.
1. Windows10/Chrome v62.0.3202.94
1. Environment: https://stage.pvdgeeks.org/
1. Steps to reproduce:
      1. Go to https://stage.pvdgeeks.org/
      1. Click on Blog Posts tab on the navigation bar
      1. Observe the blog images
1. **Expected result:** blog images are displayed
<img src="https://user-images.githubusercontent.com/25797778/33621532-0a3aa30a-d9b9-11e7-85ed-6207bcd783ec.jpg" width="30%" height="30%">

1. **Actual result:** Images do not load until page is scrolled down
<img src="https://user-images.githubusercontent.com/25797778/33621784-f1bd25d6-d9b9-11e7-95e3-405e1fe53438.gif" width="80%" height="80%">

**Comment by saimatsumoto** [comment]
Some comment from @thescientist13  below

> I think it has to do with the fact the user has already scrolled down to get to events and at that time blog posts are out of view and so at that time and hidden.  clicking the posts tab and then scrolling seems to make them appear (edited)

>[12:29] 
>could just be the interplay between `Tab` component and `LazyLoad` component.  maybe blog posts (or anything not in the first tab) just needs to programmatically triggered to show if the Tab content is lazy loaded

**Comment by thescientist13** [comment]
Nice @DevLab2425 , looking good in stage!!
