### ISSUE TITLE
Page is able to be shifted on mobile devices

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-frontend#112]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary

Summary: On mobile devices, the entire homepage is able to be shifted and retain its position. User needs to re-shift the page manually to correct the page view.
Devices/Browser:
Galaxy S5 / Chrome v53.0.2785.124
Samsung TabA / Chrome v53.0.2785.124
iPhone5c / Safari v10.0
Environment: stage.pvdgeeks.org
Exact steps to reproduce (example below)
      1. Go to stage.pvdgeeks.org on a mobile device
      1. shift the entire page to the right and observe the page
Expected result: Page is fixed in place and not able to be shifted.
Actual result: page is able to be shifted
<img width="303" alt="screen shot 2017-12-04 at 11 00 15 am" src="https://user-images.githubusercontent.com/25797778/33679221-25643596-da8c-11e7-8752-ecc668acf0fb.PNG">

**Comment by thescientist13** [comment]
I think this is cited in Lighthouse reports as well, so seems worth tracking for sure.

**Comment by paul-barry-kenzan** [comment]
This looks to be the size and length of the `<h1>`. By removing the `white-space: nowrap;` style property, the UI will _not_ scroll horizontally. Unfortunately, I don't have the time at the moment to dig in and officially resolve this.

Hope this helps.

**Comment by thescientist13** [comment]
I think I see some issues with the overall positioning / layout of the document, possibly attributed incorrectly structured Bootstrap grid classes on our end.  While working on another issue, I see a negative margin being used on the hero banner and inconsistent usage of the `row` class.

I believe `row` should be avoided within components, and instead designed to operate fluidly.  views and app shell should dictate that kind of structure, IMO.

**Comment by thescientist13** [comment]
@paul-barry-kenzan 
Indeed, that was it however I tracked it down to the `NavigationBar` component.  I think that plus organizing `row` usage a bit will be the sum of the PR I will open up.

**Comment by thescientist13** [comment]
Solid, looking good on my iPhone @DevLab2425 ! 👍
