### ISSUE TITLE
As a user I would like to see 2 events / blog posts (instead of 3) at tablet sized break points

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#113]
## Type of Change
- [ ] New Feature Request
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

New Feature Request / Improvement:
- Description: With 3 cards to display events or blog posts, the text and images become squished and truncated which starts to defeat the purpose of showing that information to the user.
- Designs: 
- Dependencies: None
- Acceptance Criteria:
  1. Should show 2 events / posts instead of 3 at tablet break points

**Comment by saimatsumoto** [comment]
- [x] TEST - Stage: events and posts are both in 2-column view
<img src="https://user-images.githubusercontent.com/25797778/34062135-108def5c-e1b9-11e7-91c0-438ad36cc023.png" width="30%" height="30%">  <img src="https://user-images.githubusercontent.com/25797778/34062154-26be899e-e1b9-11e7-9b90-2bdb1c13ec4d.png" width="30%" height="30%">  
Test device/browser: Win10 Chrome v62.0.3202.94 emulator; Samsung TabA / Chrome v53.0.2785.124

- [ ] TEST - Prod: pending
