### ISSUE TITLE
Blog details text content is not fitting properly within the container

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-frontend#125]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary

1. Blog details text content is not fitting within its container and not visible until a user shift the entire screen to the right. 
1. Device/OS: Galaxy S5 / Chrome v53.0.2785.124, iPhone5c / Safari v10.0
1. https://stage.pvdgeeks.org
1. Exact steps to reproduce (example below)
      1. Go to https://stage.pvdgeeks.org => click Blog Posts tab on a mobile device 
      1. Observe the page, shift the entire screen to the right
1. Expected result: text content fits in the container 
<img src="https://s3.amazonaws.com/hosted.pvdgeeks.org/wiki/mobile-blog-details.jpg" width="10%" height="10%">
1. Actual result: 
<img src="https://user-images.githubusercontent.com/25797778/34277529-2e6d4918-e674-11e7-885d-170b748dbee0.png" width="30%" height="30%">

**Comment by thescientist13** [comment]
related to #57

**Comment by thescientist13** [comment]
Woo @DevLab2425 , the hits just keep on coming!  🥁
