### ISSUE TITLE
Blog-details: Hero banner contents do not fit within the container 

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-frontend#127]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary

1. Hero contents in the blog-details page do not fit properly within its container on devices with 320px or smaller breakpoints. 
1. OS/Browser: 
iPhone5c / Safari v10.0
1. Environment: https://stage.pvdgeeks.org
1. Exact steps to reproduce (example below)
      1. Go to https://stage.pvdgeeks.org
      1. Click on click on "blog posts" tab and observe the hero-banner contents
1. Expected result: Hero contents fits within the container 
1. Actual result: 
<img src="https://user-images.githubusercontent.com/25797778/34306308-8664ccc6-e710-11e7-9683-42e4b9e60f1a.PNG" width="30%" height="30%">

**Comment by thescientist13** [comment]
related to #57

**Comment by thescientist13** [comment]
Crushing it @DevLab2425 💪
