### ISSUE TITLE
Copyright update in the footer before official release!

### ISSUE THREAD

**Issue by MichaelNeas** [ProvidenceGeeks/website-frontend#132]
## Type of Change
- [ ] New Feature Request
- [ X ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Awesome presentation Owen and great job everyone!

For the release, do you want copyright 2018 in the footer instead of 2017? 😁

![screenshot_20180118-193356](https://user-images.githubusercontent.com/10774848/35128947-15da82de-fc87-11e7-93b6-2735a66aa022.png)

**Comment by thescientist13** [comment]
Hi @MichaelNeas , thanks so much, glad you enjoyed the meetup!

The issue of copyright year specifically is a good question!  Technically development started last year, so 2017 I think makes sense in the context of starting year.  In the PR I noticed that you made the year dynamic.  I'm not much of a copyright expert, so I'm not sure if the typical convention is dynamic or static.  

Let me see what people in the Slack community think!

**Comment by MichaelNeas** [comment]
Sounds good, let me know what they think! :)

http://updateyourfooter.com/

I can also update my pr to include the start date to a dynamic date, (2017 - currentDate) if you prefer that convention.  I noticed the description for the spec in the footer stated "should have copyright notice with current year", which would mean the static year should get updated each year right?

https://github.com/ProvidenceGeeks/website-frontend/blob/develop/src/components/footer/footer.spec.jsx#L32

**Comment by thescientist13** [comment]
> "should have copyright notice with current year"
good catch @MichaelNeas


Your suggestion here seems like a great solution!  
> _(2017 - currentDate)_

**Comment by bjepson** [comment]
It's an excellent question. Putting the word copyright there doesn't confer any extra copyright protections in the US, and I don't know enough about other countries to know what the impacts are. If we have a compelling reason to put it there, I'd update it only when we hit a major release of the web site, just as you'd do with a book. If we are doing it for cosmetic reasons (to signal that the site is up to date) then maybe auto update it.

On a personal note, as someone who has filed dozens of copyright applications with the Library of Congress, I feel it trivializes copyright to auto update it. The copyright year has significance in terms of the history of a "work", and I'd keep the year unchanged for minor/point releases and increment when we roll out a major change.

**Comment by thescientist13** [comment]
> If we have a compelling reason to put it there, I'd update it only when we hit a major release of the web site, just as you'd do with a book.

I hadn't thought about it that way.  My only concern is remembering to update at release time, since it might seem intuitive to most (as opposed to the start of a new year)

What about the range option as @MichaelNeas proposed?
> (2017 - currentYear)

anything that updates itself is always my first choice 🤓

**Comment by thescientist13** [comment]
Hey @bjepson 
So i took a little more time to digest your feedback [here](https://github.com/ProvidenceGeeks/website-frontend/issues/132#issuecomment-358983298) and poked around a few sites as examples (GitHub, Medium, Google, Twitter) and none of them show a copyright notice.

I definitely see your point about the updating copyright.

** Final Proposal**
It really seems then the correct course of action is at best leave it at 2017 or more appropriately, just remove it all-together from the footer of the site?  (I am happy to make a new issue for this, and maybe @MichaelNeas can update his PR accordingly?

**Comment by thescientist13** [comment]
@bjepson 
What do you think of my final proposal from my above comment ^?

**Comment by bjepson** [comment]
@thescientist13 I'd favor removing it entirely. I thought about it more, and what happens if someone contributes an article to the site? I don't think we want to assert copyright over their material, but a copyright footer implies that we are asserting copyright. 

This also flows into the discussion of terms of service. Ideally, when someone contributes an article to the site, they retain copyright, but they also would give us a perpetual, non-exclusive, worldwide, transferrable, irrevocable license to us so we can republish it on our site. So a copyright footer at the bottom would muddy their ownership of it. In this case, deleting it entirely seems the way to go.

**Comment by thescientist13** [comment]
I updated the Application Design section in the [Footer section](https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design#footer) by removing the copyright requirement
