### ISSUE TITLE
Minified CSS NOT injected into the HTML

### ISSUE THREAD

**Issue by DevLab2425** [ProvidenceGeeks/website-frontend#139]
## Type of Change
- [ ] New Feature Request
- [X] Improvement / Suggestion
- [ ] Bug
- [X] Other (please clarify below)

## Summary

I have been running into a problem minifying CSS AND injecting it into the HTML using webpack. Since I’m using PvdGeeks as a guide, I noticed similar results and I wanted to raise it up here. 

Webpack is generating the mini CSS (`styles.longhash.css`), as well as a “normal” version (`styles.longhash.shorthash.css`). However when injecting, the normal version is injected rather than the minified version.

Looking at the page source, the following style file is listed, which is the “normal” version (notice _`.399f19e2.css`_)

`https://dt3s8ap74m6pw.cloudfront.net/styles.80a3b72e8745b2b77510.399f19e2.css`
![screen shot 2018-02-10 at 2 01 29 pm](https://user-images.githubusercontent.com/8385375/36065613-35e6b2f0-0e6b-11e8-8a4b-3a693944ce3a.png)

**Normal file, linked in the HTML**
![screen shot 2018-02-10 at 2 04 32 pm](https://user-images.githubusercontent.com/8385375/36065622-5d6f4594-0e6b-11e8-9810-ef4f43ace9e7.png)

By removing `399f19e2` from the path, you can access the minified version.

**Minified file, available, but not linked**
![screen shot 2018-02-10 at 2 04 23 pm](https://user-images.githubusercontent.com/8385375/36065631-7186b9ae-0e6b-11e8-8863-029211590916.png)

My suggestion/improvement is to inject the minified version into the HTML to reduce the network request size.

**Comment by thescientist13** [comment]
Great observation @DevLab2425 !  

Did a quick search and found this issue
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/434

seems like we're just not minifying our CSS in the first place?
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/434#issuecomment-282543115

However, another comment indicates that **OptimizeCssAssetsWebpackPlugn** should be doing this for us?
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/434#issuecomment-282664707

I guess it can't hurt do add this to our **ExtractTextWebpackPlugin** configuration in webpack.config.prod.js?
```javascript
options: { minimize: true }
```

**Comment by DevLab2425** [comment]
Thanks. Let me know your findings. I had `OptimizeCssAssetsWebpackPlugn`, but realized it was conflicting with `GoogleFontsPlugin` and completely removing the contents of my fonts chunk.

**Comment by thescientist13** [comment]
I tried changing it to this but no luck, was still unminified 😕 
```javascript
  rules: [
      {
        test: /\.(s*)css$/,
        use: ExtractTextPlugin.extract({
          use: [{
            loader: 'css-loader', 
            options: { minimize: true }
          },
          'sass-loader']
        })
      }
    ]
```

**Comment by thescientist13** [comment]
Maybe the issue is using both **ExtractTextWebpackPlugin** _and_ **OptimizeCssAssetsWebpackPlugin** together? 🤔

**Comment by DevLab2425** [comment]
Removing **ExtractTextWebpackPlugin** and only using **OptimizeCssAssetsWebpackPlugin** resulted in:

- 0 CSS files being generated
- All JS bundles sizes increased
- Font.css (generated by **GoogleFontsPlugin**) results in 0 bytes

**Comment by thescientist13** [comment]
0 bytes!  😮   I think you've reached peak optimization 🤣

**Comment by DevLab2425** [comment]
I'm tip-toeing the fine line between optimization and UI design. "Who needs fancy fonts anyway?"

**Comment by thescientist13** [comment]
@DevLab2425 
So I played around with the production config, and it seems to be caused by **HtmlCritcalWebpackPlugin**.  If I remove that from the plugins array, the linked CSS is minified but naturally none of the critical CSS is inlined.  

I poked around on [their repo](https://github.com/anthonygore/html-critical-webpack-plugin) but no one seems to have reported a bug around it.  Maybe it's a loading issue on our end?  In their example and [referenced article / tutorial](https://vuejsdevelopers.com/2017/07/24/critical-css-webpack/), they are also using both **HtmlWebpackPlugin** and **HtmlCritcalWebpackPlugin** in their examples.

**Comment by DevLab2425** [comment]
This is at least SOMETHING! Thanks for digging around.

**Comment by thescientist13** [comment]
@DevLab2425 
> I think the solution here is to remove the `extract: true` from the **HtmlCritcalWebpackPlugin**.

I wonder if maybe the solution here is actually to just remove **ExtractTextWebpackPlugin**?  It seems like its main feature for most use cases (CSS extraction) is already being (better?) handled by these other plugins, which we care about more.

In my case, the need for **OptimizeCssAssetsWebpackPlugin** was primarily _because_ of [duplicate CSS](https://github.com/NMFR/optimize-css-assets-webpack-plugin#solves-extract-text-webpack-plugin-css-duplication-problem) generated by **ExtractTextWebpackPlugin**
> Since extract-text-webpack-plugin only bundles (merges) text chunks, if its used to bundle CSS, the bundle might have duplicate entries (chunks can be duplicate free but when merged, duplicate CSS can be created).

So maybe this could be a great option to slim down dependencies and added processing to the production build step.  Maybe we really just need **HtmlCriticalWebpackPlugin** at the end of the day, leaving `extract: true`?

**Comment by thescientist13** [comment]
@DevLab2425 
Some interesting developments coming out of the **webpack** community around CSS that I think may be relevant here (sooner, or later) in that **webpack** now has "native" CSS support that effectively deprecates the need for **extract-text-webpack-plugin** which could potentially reduce some of the needed dependencies for some of the advanced CSS work needed for production builds.

Check out these links for more info
- https://twitter.com/wSokra/status/970253245733113856
- https://github.com/webpack-contrib/mini-css-extract-plugin
