### ISSUE TITLE
re-evaluate Babel configuration to be more future proof

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#154]
## Type of Change
- [ ] New Feature Request
- [x] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary

This is a proposal to re-evaluate the transpiled output of Babel to better reflect browser demographics and a more appropriate use of the tool [**babel-preset-env**](https://babeljs.io/docs/plugins/preset-env/) per [this post](https://jamie.build/last-2-versions) from [this tweet](https://twitter.com/jamiebuilds/status/988559577313492992).  

The goal of **babel-preset-env** was always to provide an always up to date transpilation configuration based on features that _actually_ needed to be transpiled based on the actual browsers being targeted (e.g. if all supported browsers support `import` then that feature should stay native), and thus could save a lot of additional code from being sent to the user in the way of transpiled code.  The blog post provides an alternative configuration outside of the one used currently.

### Quick Summary:
> Except, if you use babel-preset-env the way I did above. Arrow functions will never stop being compiled... no, like never ever. It could be the year 2418 and Babel will still be compiling away arrow functions.
>
> This is because of that one little "last 2 versions" bit.
>
> When you say "We support the last 2 versions of every browser", you probably don't mean browsers like:
> * Internet Explorer Mobile (0.23% market share globally)
> * Blackberry Browser (0.07%)
> * Opera Mobile (0.01%)
> * QQ Browser (0%)
> * Baidu Browser (0%)
>
> But guess what? "last 2 versions" will always match those... forever.

### Quick Recommendation (from same blog post)
>>>
```javascript
"browsers": [
  ">0.25%",
  "not ie 11",
  "not op_mini all"
]
```

Get about 87% percent of available [browser coverage](http://browserl.ist/?q=%3E0.25%25%2C+not+ie+11%2C+not+op_mini+all)
<img width="1560" alt="screen shot 2018-05-02 at 4 48 23 pm" src="https://user-images.githubusercontent.com/895923/39548460-ad6cf30a-4e28-11e8-97e9-e9bad891047a.png">

This work should probably also include work to [add Google Analytics](https://github.com/ProvidenceGeeks/website-frontend/issues/155) (so as to better monitor actual browser usage)

cc: @DevLab2425

**Comment by thescientist13** [comment]
This has also been made a formal recommendation by the Babel team 👍 
https://github.com/babel/babel/pull/7790/files

**Comment by DevLab2425** [comment]
This is a great find. I'll look to integrate myself soon. Thanks
