### ISSUE TITLE
proposal for flex box + CSS grid instead of Bootstrap

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#18]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary

Although not my core strength, for the sake of this modest website, it might make for a good opportunity to leverage native CSS layout features like Flexbox instead of relying on a dependency like Bootstrap.

Otherwise, it might make sense to at least upgrade to Bootstrap 4 (alpha-v4).

**Comment by thescientist13** [comment]
Reviewed with @Peter-holyoke and going with Bootstrap 4 seems like pragmatic middle ground, and with it's support for SASS, we can pick and choose what we want, and under the hood it uses these native CSS features.

**Comment by thescientist13** [comment]
@saimatsumoto / @ekrasner1 
This was a technical task to change a package we use for layout, to favor newer and  native CSS layout techniques.  From a UI / DevTest perspective, everything should still behave as expected, which as of this PR, is just the header.

**Comment by saimatsumoto** [comment]
- [x] TEST - Stage/QA: looks good
- [ ] TEST - Production: pending
<img width="1268" alt="stage_flexbox" src="https://user-images.githubusercontent.com/25797778/32055388-a6ae6ee6-ba2f-11e7-9c4b-7381263ecd39.PNG">

**Comment by saimatsumoto** [comment]
Known issue:
header page responsiveness: https://github.com/ProvidenceGeeks/website-frontend/issues/15
