### ISSUE TITLE
Blog post images not loading

### ISSUE THREAD

**Issue by paul-barry-kenzan** [ProvidenceGeeks/website-frontend#188]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary

1. Summary
Blog post images are displaying as missing images on the home page blog post list
1. OS/Browser, version/device used if mobile
OSX 10.12.6, Chrome 77, Laptop
1. Environment url(s)
Both Production & Staging
1. Exact steps to reproduce (example below)
      1. Go to [https://www.pvdgeeks.org/](https://www.pvdgeeks.org/) or staging
      1. Click on "Blog Posts" tab
      1. Notice missing images
1. Expected result: 
     - Should display blog post images within the grid
1. Actual result: 
    - Displays the default browser missing image icon along with `alt` text
1. Screenshot
    - <img width="910" alt="Screen Shot 2019-10-23 at 11 42 31 AM" src="https://user-images.githubusercontent.com/12274057/67410744-8e1bf680-f58a-11e9-95ec-32765f1d69e2.png">

**Comment by thescientist13** [comment]
oops.. I need to renew the SSL cert, my bad.  #151 


Will do that a later on today.

**Comment by thescientist13** [comment]
@paul-barry-kenzan 
The cert says it's not up for renewal, but I checked the site again and the images are showing.
```
$ sudo certbot renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/blog.pvdgeeks.org.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

-------------------------------------------------------------------------------

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/blog.pvdgeeks.org/fullchain.pem (skipped)
No renewals were attempted.
-------------------------------------------------------------------------------
```

Can you double check?

**Comment by paul-barry-kenzan** [comment]
@thescientist13 
That's strange. I'm still seeing the issue and have tried different browsers.

**Comment by paul-barry-kenzan** [comment]
<img width="598" alt="Screen Shot 2019-10-23 at 12 10 52 PM" src="https://user-images.githubusercontent.com/12274057/67412819-fe784700-f58d-11e9-9bbc-9721b0742343.png">
<img width="810" alt="Screen Shot 2019-10-23 at 12 10 59 PM" src="https://user-images.githubusercontent.com/12274057/67412818-fe784700-f58d-11e9-891b-44502975f7f5.png">

**Comment by thescientist13** [comment]
🤔

**Comment by thescientist13** [comment]
I went Incognito and was able to reproduce and so yeah, seems like it is cert related.
<img width="1629" alt="Screen Shot 2019-10-23 at 12 12 06 PM" src="https://user-images.githubusercontent.com/895923/67413014-6333a180-f58e-11e9-80d1-50cee68ac7f3.png">

**Comment by thescientist13** [comment]
Let me restart Apache and clear the cloudfront cache.  See if that helps eliminate any irregularities.

**Comment by thescientist13** [comment]
@paul-barry-kenzan 
Any better now?  (might want to try incognito or clear browser cache to be safe)

**Comment by paul-barry-kenzan** [comment]
Yep! Working now. Thanks @thescientist13 

Closing.

**Comment by thescientist13** [comment]
Awesome sauce 💯
