### ISSUE TITLE
slack invite link has expired

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#192]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
Clicking the Slack link in the header states that the link has expired :/
![Screen Shot 2019-10-24 at 6 53 50 PM](https://user-images.githubusercontent.com/895923/67531238-dd981a80-f68f-11e9-8f59-02a06011c9ad.png)

Thought it was supposed to be perpetual per #170, so maybe I just need to generate a new one.

**Comment by thescientist13** [comment]
Someone would just need to update the link in the [`SocialFollowLinks`](https://github.com/ProvidenceGeeks/website-frontend/blob/master/src/components/social-follow-links/social-follow-links.jsx#L18) component, to this
https://join.slack.com/t/providencegeeks/shared_invite/enQtMzI4MjA2Mzk5MDk1LWMxNDEzZDVmOWFhZDcwMmJiYTdjOGM1NTZmMzJlMGFiMWI0ODY5NTVmMGFhODQzYmY1NjkyNTJiNDU5ZDNlZmM

**Comment by doitkin** [comment]
Test Cases:  
1.  As a member of the PVDgeeks Slack (who is NOT logged in the PVDGeeks Slack workspace) or any nonmember, click the Slack link in header, expect to see "Join the Slack workspace providencegeeks . What is your email address?" (with email entry field).
2.  As a member of the PVDgeeks Slack (who is logged in the PVDGeeks Slack workspace), click the Slack link in header, and expect to see the active Slack workspace.

**Comment by thescientist13** [comment]
@doitkin 
You should be able to validate this in our staging environment now
stage.pvdgeeks.org
