### ISSUE TITLE
Create Hero Banner for Desktop

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-frontend#22]
## Type of Change
- [x] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

* Description: The Hero banner includes gallery image, logo type, logo element, and description 
* Backend Service Dependencies: None
* Capabilities:
1. Banner contains Logo type: “Providence Geeks - Connecting Digital Innovators -”
    1 .Logo element (the anchor) is placed below the logo type
    1. Brief description follows the logo element 
    1. For now, the description will be the “Mission” content from facebook.com/providencegeeks/

`“The goal of Providence Geeks is to help Rhode Island’s digital innovators connect, collaborate, and ultimately make the City-State and its geeks info-technology leaders.”`

1. All assets are horizontally and vertically aligned within the component. 
1. Static inner-banner element has 68% opacity 
1. The background image is implemented as a gallery where image changes (rotates) when:
    1. User navigate to another page and return to original page
    1. User closes the tab/window of the browser and revisit the page 
    1. User refreshes the browser page
    1. User navigates from the main page to blog details page, then goes back to the original page via:
         1. deeplinked url
         1. browser’s back button 
1. Toggle between navigation assets (Events and Blog) doesn’t trigger the background image to rotate.
1. The banner design complies with the Styleguide (url) standards.
1. The image should be responsive to the height/width of the browser window.
1. There will be no white space in the component when browser window is resized.

**Comment by thescientist13** [comment]
@saimatsumoto 
Just a heads up there some known issues
https://github.com/ProvidenceGeeks/website-frontend/pull/38#issuecomment-341419854

that should be captured and resolved as part of the mobile work
https://github.com/ProvidenceGeeks/website-frontend/issues/43

**Comment by saimatsumoto** [comment]
- [x] TEST: Stage - satisfies all requirements except for 3.4 (blog details page will be worked on later sprints)
- [ ] TEST: Prod - Pending
![stage_hero-banner](https://user-images.githubusercontent.com/25797778/32517321-06e4a1ba-c3d4-11e7-925a-59858db7c14c.gif)

**Comment by saimatsumoto** [comment]
Known issue:
For pre-loading glitch: https://github.com/ProvidenceGeeks/website-frontend/issues/78
