### ISSUE TITLE
Create Navigation Bar for Desktop

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-frontend#23]
## Type of Change
- [x] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
* Description: Navigation bar will contain events and blog assets which the users can toggle between.
* Backend Service Dependencies: None
* Capabilities:
1. Navigation bar is featured directly under the Hero Banner component.
1. The component is responsive to the browser window and there will be no whitespace when user resize the browser window.
1. Navigation assets:
    1. Assets are collectively left-aligned.
    1. Events List: navigates to selected event’s external page on click.
    1. Blog Posts: navigates to blog details page for the selected blog details page on click.
    1. Selected asset will be:
        1. In Bold Texts
        1. Underlined with a bar
        1. Hover over behavior is not active on Navigation Bar assets. 
1. The Navigation bar design complies with the Styleguide (url) standards.
1. For now, the actual Events List and Blog Posts work will be included during the development of those issues themselves, #24 and #25 , respectively

**Comment by thescientist13** [comment]
@saimatsumoto / @Peter-holyoke 
For the sake of this task, please just use some placeholder copy text where the events and blog post components would go

**Comment by saimatsumoto** [comment]
Will confirm on the fonts used for the tab with first @ekrasner1 
<img width="528" alt="events tab" src="https://user-images.githubusercontent.com/25797778/32502321-5f0bb1de-c3a8-11e7-8c80-70086b60efee.PNG">

**Comment by thescientist13** [comment]
@saimatsumoto 
What is your expectation of what the font should be?  Based on the Application Design, the predominant font should be *Josefin San*, which is what I see as the Computed Font-Family Style in Chrome DevTools for this element
<img width="1397" alt="screen shot 2017-11-07 at 11 14 49 am" src="https://user-images.githubusercontent.com/895923/32504112-0ddcfb88-c3ad-11e7-9bbe-189d7a81afad.png">

**Comment by saimatsumoto** [comment]
@thescientist13 that is the correct font family; I just need to clarify further that there's no communication gap in requirements established from original component image.

**Comment by saimatsumoto** [comment]
- [x] TEST: Stage - Looks good; satisfies all requirements except noted in #24 and #25 
- [ ] TEST: Prod - Pending 
![stage_navbar](https://user-images.githubusercontent.com/25797778/32513391-1112fe5e-c3c8-11e7-87aa-eda48d7d5b56.gif)
