### ISSUE TITLE
Create Events List for Desktop

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-frontend#24]
## Type of Change
- [x] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

### Events 
* Description: Events page will be displayed when user navigates to the landing page; or when user toggle the Blog view to Events view by selecting “Events” on Navigation Bar. It is located under the
Navigation bar and above Footer.
* Backend Service Dependencies: Meetup.com 
* Capabilities:
1. Sub-header:
   1. Is named “Upcoming Events.
   1. Is vertically left-aligned.
1. List is displayed in two-row and three-column format until reaching “Load More” button.
   1. Column will remain in three-row format.
   1. On mobile screen, the list is displayed in three-row and two-column format.
       1. Colum will remain in two-column format.
       1. "Load More" button will not be displayed on mobile screens.
1. Event images are static fed via events API.
   1. Vertically center-aligned within its field.
1. Event name is featured at the bottom of the event image; vertically center-aligned.
1. Clicking on Event Name navigates user to the corresponding event's page in meetup.com.
1. Event Description:
   1. Featured below the Event image
   1. Word Limit: 160 characters.
   1. Fits to the image width.
   1. Text contents are left-aligned within the field.
   1. The contents are fed via events API.
1. Date/Time is also fed via Events API.
   1. Featured at the bottom-left of each event.
   1. Vertically left-aligned within its field.
   1. Date format: MM/DD/YY
   1. Time format: HH:mm AM/PM
1. Share Call-to-Action Social icons:
   1. Featured next to the Date/Time.
   1. Vertically right-aligned.
   1. User clicks on the Facebook or Twitter icons in order to share.
      1. Clicking on either icons will open a new pop up window.
         1. On a mobile device, it opens the user's native app if available.
      1. Navigates to a user’s Facebook or Twitter accounts to share the event's link.
1. Load More button:
   1. On click, two more rows of events will load.
   1. If there are three or less events left to load, only one more row will be loaded.
   1. Load More button will not be displayed when accessed from a mobile device.
1. Events are ordered chronologically (determined by Date/Time).
   1. Upcoming events with closer dates (to the current date) will be on the top.
1. Infinite Scrolling (mobile exclusive feature):
   1. When user scrolls at the end of the page, the page will load more blog contents.
   1. If there is no more content to display, it will display the comments.
   1. If no more contents to load, yields no action.
   1. Loader will be displayed when loading the content
1. Hover over function is not active on Events List page.
1. Events page design complies with the [Styleguide](https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design#styleguide) standards.
1. Component and all assets should be responsive to the screen size.
* **Image:**
<img src="https://s3.amazonaws.com/hosted.pvdgeeks.org/wiki/events-list.jpg" width="25%" height="25%">

**Comment by thescientist13** [comment]
An missing dependency / feature request has been identified on the **website-lambda-meetup** repo (Good catch @saimatsumoto !)
https://github.com/ProvidenceGeeks/website-lambda-meetup/issues/11

Essentially we need to make an improvement to return an image for an event.  However, the Meetup.com API does not return one for an event, but we _can_ get the image for a Meetup group.

Without this feature, this should only impact the ability to show an image.  Maybe we should have a default thumbnail image as a back up?

**Comment by thescientist13** [comment]
@saimatsumoto / @ekrasner1 
Couple known issues
1.  Images are missing, but that will need some back end updates.  
    * Tracking the backend changes - https://github.com/ProvidenceGeeks/website-lambda-meetup/issues/11
    * Tracking the frontend change - https://github.com/ProvidenceGeeks/website-frontend/issues/58
1.  Updated the layout a bit to better compact the information
Screen Shot 2017-11-10 at 3.30.13 PM

**Comment by saimatsumoto** [comment]
- [x]TEST: Stage-displayed as expected.
- [ ]TEST: Production-awaiting next deployment.

**Comment by saimatsumoto** [comment]
Known issues:
Events list page responsiveness: https://github.com/ProvidenceGeeks/website-frontend/issues/65
Pre-loading issue: https://github.com/ProvidenceGeeks/website-frontend/issues/78
