### ISSUE TITLE
Add a favicon image for the website

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#26]
## Type of Change
- [x] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

1. A favicon (probably just a .png) of the PVD Geeks logo would suffice, in an _images_ directory in the **bootstrap** component
1. Integrate it with [**favicons-webpack-plugin**](https://github.com/jantimon/favicons-webpack-plugin) for production builds

cc: @saimatsumoto / @Peter-holyoke

**Comment by thescientist13** [comment]
![pvd-geeks-logo-denim](https://user-images.githubusercontent.com/895923/31953187-8bbb6f88-b8b0-11e7-9ed9-c82e0837a1ce.png)

**Comment by thescientist13** [comment]
Will need a spot for this documented in the Application Design I reckon

**Comment by saimatsumoto** [comment]
@thescientist13  Initial update has been made to the [Application Design](https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design)
- [x] TEST: Stage - Looks good; Favicon is displayed on the tab and shows when the site is selected as a favorite. 
- [ ] TEST: Production - pending
