### ISSUE TITLE
have header links open in browser tab

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#27]
## Type of Change
- [ ] New Feature Request
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

To ensure engagement with the site, it would be a better user experience (IMO) if clicking the FB, Twitter, or Slack links opened in a browser.

cc: @ekrasner1 / @saimatsumoto / @Peter-holyoke

**Comment by saimatsumoto** [comment]
- [x] TEST
   Looks good in Stage; all the Social Network links open in a new browser tab. 
![stage_new tab](https://user-images.githubusercontent.com/25797778/31952838-9053030e-b8af-11e7-81c6-6f0afc2d9e09.gif)

**Comment by saimatsumoto** [comment]
**Known issue:**
links should open in native app on mobile if available: https://github.com/ProvidenceGeeks/website-frontend/issues/81
