### ISSUE TITLE
social networking sites (SNS) icons not showing in the header

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#28]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary

**Expected**: Icons should show like the [Application Design](https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design#header)

**Actual**: Icons do not show on [stage](https://s3.amazonaws.com/providencegeeks.com/frontend/stage/index.html), looks like they are dark and hidden in the corner. 
<img width="1413" alt="screen shot 2017-10-23 at 8 57 05 pm" src="https://user-images.githubusercontent.com/895923/31920109-ce35a058-b834-11e7-866f-2ef350161a9f.png">

Seems like a result of this PR I just merged - #21 .  the irony... 🤦‍♂️ 

cc: @ekrasner1 / @saimatsumoto

**Comment by saimatsumoto** [comment]
- [x] TEST 
Looks good in Stage.

![stage_header](https://user-images.githubusercontent.com/25797778/31952449-9e61a0b4-b8ae-11e7-81a9-8d93525fa378.gif)

**Comment by saimatsumoto** [comment]
Known issue:
header page responsiveness (center-align): https://github.com/ProvidenceGeeks/website-frontend/issues/15
