### ISSUE TITLE
create a reusable social network links component

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#33]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary

Based on the work to create a header and footer components ( #6 / #7), this is a technical task to 
1.  Create a reusable *social-network-links* component
1.  Encapsulate the common JS / CSS used for showing these in both the header and the footer
1.  Create unit tests

**Comment by thescientist13** [comment]
@saimatsumoto 
This was a technical refactoring task, so please give everything a once over, in particular around the Social Networking icon functionality in the header / footer

**Comment by saimatsumoto** [comment]
Social Networking icon functionality in the header/footer work as expected.
