### ISSUE TITLE
Setup Domain Name System 

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-frontend#34]
## Type of Change
- [x] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Other (please clarify below)

## Summary
This setup enables [Production Environment](https://github.com/ProvidenceGeeks/website-docs/wiki/Technical-Architecture#production-environment) to point to the AWS network of services. 
- [x] http://www.pvdgeeks.org : Route 53 -> Prod Cloudfront Distribution -> Prod S3 Bucket
- [x] http://stage.pvdgeeks.org : Route 53 -> Stage Cloudfront Distribution -> Stage S3 Bucket

**Comment by thescientist13** [comment]
Can also setup a staging domain as well, e.g. stage.providencegeeks.com

**Comment by thescientist13** [comment]
@saimatsumoto / @ekrasner1 
Stage and Prod URLs working!!  🎉

**Comment by saimatsumoto** [comment]
Thank you very much, Owen!


Sai Matsumoto
DevTester
smatsumoto@kenzan.com<mailto:jonetime@kenzan.com>


________________________________

**Comment by saimatsumoto** [comment]
Both urls looks good:
 http://www.pvdgeeks.org
 http://stage.pvdgeeks.org
