### ISSUE TITLE
setup API Gateway for API routing

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#35]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary

- [ ] API Gateway to route to EC2 endpoints (events, posts)
- [ ] Connect Stage / Prod Cloudfront Distributions -> API Gateway

**Comment by thescientist13** [comment]
Events API is working!
```
$ curl -I http://stage.pvdgeeks.org/api/events
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 150091
Connection: keep-alive
Date: Sat, 04 Nov 2017 16:16:05 GMT
x-amzn-RequestId: 75a22c54-c17b-11e7-bee1-d12d28e41d70
X-Amzn-Trace-Id: Root=1-59fde7c5-e2297bf1674dff0dc104e9c5
Via: 1.1 17ebdffe6ca6e09df7d69af286cbc07c.cloudfront.net (CloudFront), 1.1 8f18deab0e501ffbd2fa94cfd46e4785.cloudfront.net (CloudFront)
Age: 234
X-Cache: Hit from cloudfront
X-Amz-Cf-Id: Af1IFCnhrLgPB0nowWN7mT7k_d0EUDYZ1TbU-lPWxLFAZVwF6nM6UQ==
```

**Comment by thescientist13** [comment]
See the full response by viewing `http://stage.pvdgeeks.org` in your browser

**Comment by saimatsumoto** [comment]
- [x] TEST: Looks good in both environments below; all upcoming events for [respective meetup](https://github.com/ProvidenceGeeks/website-docs/wiki/API-Specification#events) are listed.
http://stage.pvdgeeks.org/api/events
http://www.pvdgeeks.org/api/events
