### ISSUE TITLE
get images for hero banner

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#42]
## Type of Change
- [ ] New Feature Request
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

Currently the Hero Banner component just displays a placeholder background.  Picture of Rhode Island in the Application Design should be used instead.  I think 3-5 pictures would be good.

@Peter-holyoke 
Can you please speak to:
- the dimensions used / needed
- will we went mobile and desktop versions of these images?

- Once the new images are available, update Hero-Banner section in [Application Design](https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design) with appropriate image(s) @saimatsumoto

**Comment by Peter-holyoke** [comment]
I would say that we should go with 1920x1080, so that it can scale down appropriately to all screen sizes. 

But we could use media queries and have multiple images that fit each bootstrap breakpoint so that we have more control over how we want it to look. Getting all those images could be a bit of a pain, but it is an option.

**Comment by thescientist13** [comment]
Makes sense @Peter-holyoke .  I think for an image that big, we should see / confirm if we load the image asynchronously, or maybe with a fade in :o !  But that's just me thinking out loud. 🙃
 
If this gets integrated with the CMS, that might be the right opportunity to add support for mobile and desktop images, since maybe there would be a WordPress plugin to automatically resize?  

Made a ticket for tracking the CMS feature request here: https://github.com/ProvidenceGeeks/website-backlog/issues/9

**Comment by thescientist13** [comment]
I worked with Elana and reached out in Slack for submissions

**Comment by thescientist13** [comment]
Thanks for the images @saimatsumoto / @ekrasner1 !

@Peter-holyoke 
Plus update the hero banner to randomly pull from these image paths
- https://s3.amazonaws.com/hosted.pvdgeeks.org/website/hero-banner/hero-image-1.jpg
- https://s3.amazonaws.com/hosted.pvdgeeks.org/website/hero-banner/hero-image-2.jpg
- https://s3.amazonaws.com/hosted.pvdgeeks.org/website/hero-banner/hero-image-3.jpg
- https://s3.amazonaws.com/hosted.pvdgeeks.org/website/hero-banner/hero-image-4.jpg
- https://s3.amazonaws.com/hosted.pvdgeeks.org/website/hero-banner/hero-image-5.jpg

**Comment by saimatsumoto** [comment]
I will track below in https://github.com/ProvidenceGeeks/website-docs/issues/34. 
Once the new images are available, update Hero-Banner section in Application Design with appropriate image(s) @saimatsumoto
