### ISSUE TITLE
Make Hero Banner Responsive

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-frontend#43]
## Type of Change
- [ ] New Feature Request
- [x] Improvement / Suggestion

## Summary

The letters are all squished and is cause issues at mobile breakpoints

**Comment by saimatsumoto** [comment]
@mdiwale @thescientist13 @ekrasner1 
Looks well responsive on samsung galaxy S5 but iOS may need more padding on left/right. 
Galaxy S5 / Chrome v53.0.2785.124
<img src="https://user-images.githubusercontent.com/25797778/34181079-ded77efa-e4de-11e7-9b76-666c9881cecb.png" width="30%" height="30%">
iPhone5c / Safari v10.0
<img src="https://user-images.githubusercontent.com/25797778/34180955-7b98ff44-e4de-11e7-92ee-d8aaa957da9e.PNG" width="30%" height="30%">

**Comment by thescientist13** [comment]
@saimatsumoto 
Updates made to cover https://github.com/ProvidenceGeeks/website-frontend/issues/43#issuecomment-352901947

**Comment by saimatsumoto** [comment]
Title banner is now displayed with enough padding ![stage_hero_fix](https://user-images.githubusercontent.com/25797778/34227897-c6bd3634-e59c-11e7-84d4-aedff5696254.PNG)
