### ISSUE TITLE
setup API Gateway for Posts API routing

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#46]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary

- [ ] API Gateway to route to EC2 endpoints (posts)

**Comment by thescientist13** [comment]
- Stage API Gateway: https://o0j6acf0zd.execute-api.us-east-1.amazonaws.com/staging/api/posts
- Stage: https://stage.pvdgeeks.org/api/posts
- Prod API Gateway: https://o0j6acf0zd.execute-api.us-east-1.amazonaws.com/production/api/posts
- Prod: https://www.pvdgeeks.org/api/posts

**Comment by saimatsumoto** [comment]
- [x] TEST: Stage-data returns
![stage_posts api](https://user-images.githubusercontent.com/25797778/33574189-48d93576-d906-11e7-8cba-8e152a655f78.gif)
- [x] TEST: Production-data returns
![prod_posts api](https://user-images.githubusercontent.com/25797778/33574192-4c851ed8-d906-11e7-8007-dddfd5de753a.gif)
