### ISSUE TITLE
As a user I should see an error message if there is an error retrieving events data

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-frontend#51]
## Type of Change
- [x] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

Implement messages to convey errors/notifications/information in a graceful manner when:
1. When a malformed data returns, users will see a error message which explains that an error occurred.  
2. When no data returns and no content to display, user will see a message which provides information related to why users can't see the contents.

**Comment by thescientist13** [comment]
@saimatsumoto 
We should specify this per feature, e.g. one for events list, another for blog posts, etc

**Comment by thescientist13** [comment]
@saimatsumoto / @ekrasner1 
Could you suggest:
1. What the copy text would be?
1. How should it be presented?  Something like [Bootstrap's Alerts component](https://getbootstrap.com/docs/4.0/components/alerts/) would be simple enough.

**Comment by saimatsumoto** [comment]
@thescientist13 Confirmed with @ekrasner1 
1. Copy text: please use simple error message for now (ex: 404 Page Not Found, 500 Internal Server Error, etc.) 
2. Presentation: +1 for presentation in the source link.

**Comment by thescientist13** [comment]
Hmmm, I'm not sure I would want to show those as a message to the user?
> 500 Internal Server Error

I was thinking something more generic and helpful like
> Sorry, unable to load <blah> right now.  Please try again or contact us at xxx if the problem persists.

**Comment by saimatsumoto** [comment]
@ekrasner1 gives 👍
