### ISSUE TITLE
As a user I should see an error message if there is an error retrieving Blog Posts

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-frontend#52]
## Type of Change
- [x] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

Implement messages to convey errors/notifications/information in a graceful manner when:

When a malformed data returns, users will see a error message which explains that an error occurred.
When no data returns and no content to display, user will see a message which provides information related to why users can't see the contents.

**Comment by thescientist13** [comment]
Like #51 , this just needs copy / treatment

**Comment by saimatsumoto** [comment]
@thescientist13 as per @ekrasner1 , below message format is agreed upon. 
> Sorry, unable to load { blah } right now. Please try again or contact us at xxx if the problem persists.

**Comment by thescientist13** [comment]
In light of the completion of #168 / #176 , this should be pretty easy to implement now.

cc: @tmelliottjr
