### ISSUE TITLE
As a user I would like a details page for viewing Blog Posts

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-frontend#57]
## Type of Change
- [x] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

* **Description:** Blog details page will contain a Hero-banner, Blog contents, Social icons and other sharing methods.
* **Backend Service Dependencies:** [Posts API](https://github.com/ProvidenceGeeks/website-docs/wiki/API-Specification#posts)
* **Capabilities:**
    1. Hero banner: featured image on the Blog Posts becomes the hero banner image.
        1. Includes Blog title, author, and date.
        1. Collectively center-aligned.
        1. Title is featured at the top.
        1. Author and Date are featured under the title.
        1. Date format: MM/DD/YY
    1. Blog contents are featured below the banner.
        1. On mobile screens, Social icons are featured under the banner.
        1. Blog content is displayed in a single column.
        1. A user scrolls down to read the full contents of the blog.
    1. Blog image - fed via Posts API; location is determined by Content Manager.
        1. Center-aligned within its field.
        1. Caption is featured under the image.
            1. Center-aligned within its field.
            1. Caption fed via Posts API.
    1. Sub-Headline is fed via Posts API.
    1. Share Social Icons:
        1. Icons are located at the left-top by the blog content, vertically oriented.
        1. On mobile screens, horizontally oriented.
    1. Facebook, Twitter, and LinkedIn icons
        1. User clicks on the Facebook, Twitter, and LinkedIn icon in order to share the blog link.
        1. Clicking on either icons will open a new tab.
            1. On a mobile device, it opens the user’s native app if available.
        1. Navigates to a user’s Facebook or Twitter accounts to share the blog link.
            1. Facebook share prepopulates the blog link to be shared. 
            1. Twitter share prepopulates default message:`<"Title of Blog"> from @ProvidenceGeeks <Blog link>`
    1. Clicking on the mail icon will open a new window to open user’s email.
        1. On a mobile device, it opens a the user's default email in the native app if available.
        1. Clicking on Print will open the Printing console to print the blog in PDF format.
            1. Print icon will not be displayed when accessed by a mobile device.
    1. There will be no hover-over function on the blog details page.
    1. Blog details page design complies with the [Styleguide](https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design#styleguide) standards.
    1. Component and all assets should be responsive to the screen size.
* **Image:** TBD (awaiting updates)

**Comment by thescientist13** [comment]
@saimatsumoto 
Could you please update the A.C. here to reflect the comments portion of the A.C. is being handled in another issue (#80)

**Comment by saimatsumoto** [comment]
@thescientist13 the text content is not fitting properly within the article container. User will not be able to see the text content until shifting the entire screen to the right. 

![blog-details_text content fit](https://user-images.githubusercontent.com/25797778/34277529-2e6d4918-e674-11e7-885d-170b748dbee0.png)

Device/OS: Galaxy S5 / Chrome v53.0.2785.124, iPhone5c / Safari v10.0

**Comment by thescientist13** [comment]
Good catch @saimatsumoto .  Please open a bug for this issue and I will take a look today.
