### ISSUE TITLE
Events List images are missing

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#58]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary

During the completion of #24, it was realized images are not always available for events.  To support
1. Implement feature request in **website-lambda-meetup** requesting images get added to saved data response - https://github.com/ProvidenceGeeks/website-lambda-meetup/issues/11
1. Map that property to events object modeled and returned by Events API - https://github.com/ProvidenceGeeks/website-api-events/issues/16

Once those have been added and deployed, this issue can be implemented.

cc: @saimatsumoto

**Comment by thescientist13** [comment]
As part of this, may want to update our current fallback images text / color.  But also, might be good to have a formal fallback image component.  (with a fallback image provided by @ekrasner1 )

**Comment by saimatsumoto** [comment]
Events list images are now returning as expected. 
![stage_events list](https://user-images.githubusercontent.com/25797778/33043135-50462ec6-ce12-11e7-8c56-7c3cc67877d2.gif)
