### ISSUE TITLE
improve unit testing of nested components

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#60]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary

In a React unit test where nested components are involved, instead of testing that a component's `className` can be found, the component itself should be tested directly.

#### Before
```
it('should have a NavigationBar component', () => {
  expect(home.find('div.navigation-bar').length).toEqual(1);
});
```

#### After
```
import NavigationBar from '../../components/navigation-bar/navigation-bar';

// ...

it('should have a NavigationBar component', () => {
  expect(home.find(NavigationBar).length).toEqual(1);
});
```

**Comment by thescientist13** [comment]
Note, I think non `class` based components (like the icon / logo components) would need to be converted since they would be subclassed from `React.Component`

**Comment by thescientist13** [comment]
@saimatsumoto 
Did a fair amount of refactoring around unit testing and components, please give everything a once over on stage.

**Comment by saimatsumoto** [comment]
Current features are functioning as expected.
