### ISSUE TITLE
Navigation bar is not responsive to mobile screen size 

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-frontend#64]
## Type of Change
- [x] Bug

## Summary

Navigation tabs are not responsive on screen size smaller than 320px.
1. Windows10/Chrome v62.0.3202.94, iPhone5c/iOS 10.3.3
1. http://stage.pvdgeeks.org/
1. Exact steps to reproduce (example below)
      1. Go to http://stage.pvdgeeks.org/ on a mobile device
      1. locate and observe the navigation bar 
1. Expected result: Navigation bar is responsive to screen sizes.
1. Actual result: Navigation tabs stack on top of one another on mobile view.
<img src="https://user-images.githubusercontent.com/25797778/32905512-299ccf34-cac8-11e7-9920-61b4443c328f.PNG" width="30%" height="30%">

**Comment by thescientist13** [comment]
Might have been on me from #60

**Comment by saimatsumoto** [comment]
Currently displayed as expected. 
<img src="https://user-images.githubusercontent.com/25797778/32971704-865b6966-cbbc-11e7-9318-1038c2fe07aa.PNG" width="30%" height="30%">
