### ISSUE TITLE
Events list is not responsive to the screen size 

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-frontend#65]
## Type of Change
- [x] Bug

## Summary

Events list is not responsive to mobile screen size; event contents/assets do not align correctly when observed in mobile view.
1. Windows10/Chrome v62.0.3202.94, iPhone5c/iOS 10.3.3/Safari v10.0
1. http://stage.pvdgeeks.org/
1. Exact steps to reproduce (example below)
      1. Go to http://stage.pvdgeeks.org/ on a mobile device
      1. locate and observe the events list
1. Expected result: 
    1. Contents do not align correctly on mobile (320px) view; two-column, three-rows and each event content is displayed the same way it does on the desktop view (320px<).
    1. Mobile view should load 3 rows at a time for further contents.
    1. Contents align as it does on the desktop view on tablet (768px).
1. Actual result: 
    1. Contents do not align correctly on mobile (320px) view.
    1. On Mobile, load further contents displays 6 rows of further contents.  
    1. Contents do not align correctly on tablet (768px) view.

Mobile: 
<img src="https://user-images.githubusercontent.com/25797778/32907645-b83a6822-cace-11e7-9359-323b4253ca2f.PNG" width="30%" height="30%">
Tablet:
<img src="https://user-images.githubusercontent.com/25797778/32907981-18727102-cad0-11e7-8bf3-738f0425ff60.png" width="30%" height="30%">

**Comment by thescientist13** [comment]
ooph.  yeah, likely an issue I introduced in the refactoring I did at the end of #24

**Comment by saimatsumoto** [comment]
This is fixed on screens larger than 360px; descriptions still break the format on 320px (on iPhone5 iOS 10.3.3). 

<img src="https://user-images.githubusercontent.com/25797778/32971564-c3960102-cbbb-11e7-964e-89639547132f.PNG" width="30%" height="30%">

**Comment by thescientist13** [comment]
Maybe we'll need an autoprefixer or something.  Perhaps that older version of iOS doesn't support some of the flexbox rules we're using.

**Comment by thescientist13** [comment]
@saimatsumoto 
Can you confirm what version of Safari this was reproduced with?

**Comment by saimatsumoto** [comment]
iOS 10.3.3 @thescientist13

**Comment by thescientist13** [comment]
that's iOS version.  I was looking for the version of Safari (the browser)

**Comment by saimatsumoto** [comment]
Added Safari version (10.0) in the original description.

**Comment by saimatsumoto** [comment]
The issue is no longer reproducible. 
Device/OS: iPhone5 iOS 10.3.3 / Safari v10.0
![stage_events-list_iphone5](https://user-images.githubusercontent.com/25797778/34261998-05238756-e639-11e7-96db-113c60cc7169.PNG)
