### ISSUE TITLE
create a Footer Component

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#7]
## Type of Change
- [x] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

New Feature Request / Improvement:
- Description: A footer to show a copyright and contact related link to PVD Geeks based on the Application Design [here](https://github.com/ProvidenceGeeks/website-docs/wiki/Application-Design#footer)
- Designs: See Application Design link above ^
- Dependencies: Designs / Application Design
- Acceptance Criteria: Referencing the Application Design link
1. Show a copyright copyright `Providence Geeks 2017`
1. Show Facebook logo with link to Providence Geeks [Facebook page](https://www.facebook.com/providencegeeks/)
1. Show Twitter logo with link to Providence Geeks [Twitter profile](https://twitter.com/providencegeeks)

**Comment by saimatsumoto** [comment]
- [x] TEST: [Stage](stage.pvdgeeks.org) - all requirements are covered and work as expected. 
- [ ] TEST: [Production](www.pvdgeeks.org) - pending
![stage_footer](https://user-images.githubusercontent.com/25797778/32175446-63e8c19a-bd5b-11e7-8029-e86a7e364f54.gif)

**Comment by saimatsumoto** [comment]
Known issues:
Component responsiveness: https://github.com/ProvidenceGeeks/website-frontend/issues/17
