### ISSUE TITLE
Inline critical CSS to boost Lighthouse performance score (Lighthouse round 2)

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#72]
## Type of Change
- [ ] New Feature Request
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

Continuing from #59 / #69 I had to pull the inline critical CSS feature since it wasn't deploying correctly to S3.  This is to track this and other recommendations to continue to improve the site's overall performance to better than 62
<img width="647" alt="screen shot 2017-11-20 at 3 03 18 pm" src="https://user-images.githubusercontent.com/895923/33039011-8a8de7da-ce04-11e7-9611-83731b6cfde3.png">

<img width="601" alt="screen shot 2017-11-20 at 3 11 18 pm" src="https://user-images.githubusercontent.com/895923/33039176-20dc9c9a-ce05-11e7-955e-c834aa6ca40b.png">

**Comment by thescientist13** [comment]
Well our score went up every so lightly, because it's now getting offset by the images we're loading in the events card lol 🤷‍♂️ 

Progress comes one  KB at a time I guess.  I will make another issue for improving the image loading experience.

**Comment by thescientist13** [comment]
Looks like this has introduced another small issue, see #78 .  Since it requires a nuanced / balanced approach for providing the best user experience, we should probably track it or roll this back if we don't like what's there

**Comment by saimatsumoto** [comment]
Validated that it reflects reduced render-blocking stylesheet. 
<img width="1274" alt="stage_performance_lighthosue" src="https://user-images.githubusercontent.com/25797778/33092894-80ae4730-cec9-11e7-806d-be932cb2eb81.PNG">
