### ISSUE TITLE
lazy load images to improve Lighthouse performance score (Lighthouse round 3)

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#75]
## Type of Change
- [ ] New Feature Request
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

Continuing from #59 / #69 / #72 there are now recommendations for image loading, this wasn't so much an issue before but as merged #68 at the same time as #72 , it basically offset our gain.  

Some of these images come from Meetup.com, so that may impact the full extent of what we can do here.

### Current Lighthouse score at time of this ticket
<img width="817" alt="screen shot 2017-11-20 at 8 44 59 pm" src="https://user-images.githubusercontent.com/895923/33050608-bd84d688-ce33-11e7-9ca2-a838cdcc01df.png">

### Lighthouse Recommendations
<img width="848" alt="screen shot 2017-11-20 at 8 45 08 pm" src="https://user-images.githubusercontent.com/895923/33050638-e875e27e-ce33-11e7-81b2-27b10d1e2173.png">

**Comment by thescientist13** [comment]
Summary of changes
https://github.com/ProvidenceGeeks/website-frontend/pull/76
https://github.com/ProvidenceGeeks/website-frontend/pull/76#issuecomment-346856266

New score, stayed the same though, but I think the UX is better
<img width="860" alt="screen shot 2017-11-25 at 3 52 41 pm" src="https://user-images.githubusercontent.com/895923/33234673-2945fd52-d1f9-11e7-9964-8ada9f3cefa7.png">

**Comment by saimatsumoto** [comment]
- [x] TEST: Validated that lazy loading is implemented and improved lighthouse score slightly. 
<img width="1275" alt="stage_performance" src="https://user-images.githubusercontent.com/25797778/33279255-f82bfa5e-d36b-11e7-805e-a9b5c630eb98.PNG">
