### ISSUE TITLE
Improve the visual aspect of upfront loading when page navigation and/or refresh is rendered

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-frontend#78]
## Type of Change
- [ ] New Feature Request
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

Currently, when a user navigates to stage.pvdgeeks.org and/or refreshes the page, a flash of upfront loaded images are displayed prior to the complete page load; which occurs intermittently.

Looks like its the logo SVG before the CSS is applied to it. May be able to change the SVG so that it is smaller by default, so that this doesn't happen.
![stage_flash upfront loading](https://user-images.githubusercontent.com/25797778/33085684-5a6897f8-ceb3-11e7-9475-49d469ad96bb.gif)

**Comment by thescientist13** [comment]
seems related to #72 .  It will be a matter of finding a compromise between these two options I feel

1) FOUC (flash of unstyled content): you get a smaller payload immediately by only loading critical code, at the expense of a brief flash (what you see now).  As implemented in #72 
https://en.wikipedia.org/wiki/Flash_of_unstyled_content

or

2) Upfront loading: wait for all assets to load, then render (what we had before).

so number 2 is a "better" user experience performance wise, but does have that brief flash.

Perhaps we can 
1. Resize the SVG

1. Or consider these styles critical and make sure they get inlined (maybe by moving them into the `Bootstrap` component's SCSS file

**Comment by thescientist13** [comment]
Here's a relevant section from the penthouse FAQ, which is at the core of **critcal**
https://github.com/pocketjoso/penthouse#unstyled-content-showing-when-using-the-critical-css

**Comment by thescientist13** [comment]
this seems to have been solved and seen as gone away in latest iterations of the project, especially in the 0.3.0 work in stage.
