### ISSUE TITLE
Social Links on Header/Footer are not spaced correctly : Android mobile

### ISSUE THREAD

**Issue by kpisano** [ProvidenceGeeks/website-frontend#82]
## Summary
On the Android Samsung S7 Edge, the social media icons (Facebook, Slack, and Twitter) are not spaced properly.
1. Exact steps to reproduce 
      1. Go to stage.pvdgeeks.org
      1. Look at Header and Footer
1. Expected result: Icons are spaced appropriately
1. Actual result: Icons are touching each other
![screenshot_20171122-160149](https://user-images.githubusercontent.com/26802018/33149668-8f24897a-cf9e-11e7-9b4b-be786aecd6d5.png)

**Comment by thescientist13** [comment]
probably related to this outstanding issue
https://github.com/ProvidenceGeeks/website-frontend/issues/43
