### ISSUE TITLE
Use properly sized images

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#84]
## Type of Change
- [ ] New Feature Request
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

As part of getting into compliance with Lighthouse, it was observed some of the image sizes being returned are quite large in size.  It looks like the Meetup Lambda is using the `highres_link` from the Meeup.com API
https://github.com/ProvidenceGeeks/website-lambda-meetup/blob/master/src/index.js#L44
```javascript
// Build object containing group name, and associated group image.
groups.map(group => {
  groupImages[group.urlname] = group.group_photo !== undefined ? group.group_photo.highres_link : null;
});
```

This has resulted in a poor performance score
<img width="798" alt="lighthouse-lazyload-after-properly-size-images" src="https://user-images.githubusercontent.com/895923/33234929-af1a6c9e-d1fc-11e7-9308-dab5c48ee770.png">

This is track the impact of making that change in and its deployment

**Comment by thescientist13** [comment]
Lighthouse score went up, but only went up 1 pt 😞 
<img width="825" alt="lighthouse-performance-after-optimize-meetup-assets" src="https://user-images.githubusercontent.com/895923/33235179-f2300a80-d200-11e7-8ed8-99f158fdd8d6.png">

No other recommendations though... 🤔

**Comment by saimatsumoto** [comment]
- [x] TEST: Performance score went up slightly and "User properly sized images" is no longer suggested (nor any other suggestions).
<img width="1275" alt="stage_performance" src="https://user-images.githubusercontent.com/25797778/33279086-5dc80b60-d36b-11e7-9eb1-01b4ed1be87d.PNG">
