### ISSUE TITLE
optimize CSS bundles by removing duplicate CSS

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#87]
## Type of Change
- [ ] New Feature Request
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

A lot of the CSS is being loaded twice, likely due to duplicate `@import` within `.scss` files.  We have 120 KB of styles because of this
https://d2b64jbw6hxz4f.cloudfront.net/styles.56091d8dad2cc72fdf36.b0341d3c.css

This could likely be having a (not) obvious impact to our time to first meaningful paint.  Hope this increase our current lighthouse score, which currently stands at this for Performance
![lighthouse-performance-before-optimizing-css](https://user-images.githubusercontent.com/895923/33241332-d209e410-d291-11e7-8b74-052774cccc00.png)

**Comment by thescientist13** [comment]
Look at this!  🎉  👀 

After removing duplicate CSS, we now have a much smaller CSS bundle (11 KB!)
![screen shot 2017-11-26 at 10 14 34 am](https://user-images.githubusercontent.com/895923/33241431-2407a83c-d293-11e7-8f60-da232aad1c16.png)

And that reduced our time to first meaningful paint by a whole second, which got our Lighthouse score up by 9 points and into the green!!! 💚 
![lighthouse-performance-after-optimize-css](https://user-images.githubusercontent.com/895923/33241445-640ca5d6-d293-11e7-9b1e-c818170ed04d.png)

**Comment by thescientist13** [comment]
This change also seems to have greatly improved https://github.com/ProvidenceGeeks/website-frontend/issues/78, in that I very rarely see it, and when I do, it goes away a lot quicker

**Comment by saimatsumoto** [comment]
- [x] TEST: Stage - performance wend down and well under 5000 millisecond, CSS bundle is down to 11.05 KB.
<img width="1275" alt="stage_performance" src="https://user-images.githubusercontent.com/25797778/33278138-96f58ef6-d368-11e7-8ad5-193c76c06e9e.PNG">

- [ ] TEST: Production - awaiting next deployment to reflect this change
