### ISSUE TITLE
CORS Issue for the Canter font

### ISSUE THREAD

**Issue by Peter-holyoke** [ProvidenceGeeks/website-frontend#90]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary

Bug:
1. Summary: CORS error message for the Canter font in staging environment.
1. OS X 10.12.6 - Chrome/62.0.3202.94
1. [http://stage.pvdgeeks.org/](http://stage.pvdgeeks.org/)
1. Exact steps to reproduce
      1. Go to [http://stage.pvdgeeks.org/](http://stage.pvdgeeks.org/)
      1. Wait for page to load
1. Expected result: "Providence Geeks" text should render in the Canter font.
1. Actual result: It renders in default font.
1. Error message: 
```no-highlight
Access to Font at 'http://d2b64jbw6hxz4f.cloudfront.net/bc517149950afc2999fdec6f2e1bf064.otf' from origin 'http://stage.pvdgeeks.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://stage.pvdgeeks.org' is therefore not allowed access.
```
1. Screenshot
<img width="1274" alt="bug_hero-banner-font" src="https://user-images.githubusercontent.com/32274225/33391563-78cc99c4-d507-11e7-8dbf-d012aab6ffc3.png">

**Comment by thescientist13** [comment]
for whatever reason this issue has gone away.  still tracking it as part of a release though just in case.

**Comment by kpisano** [comment]
as of 12/5 this issue doesn't happen on Macbook Pro with Chrome 62.0.3202.94

**Comment by thescientist13** [comment]
great, thanks for confirming @kpisano !

**Comment by saimatsumoto** [comment]
No longer reproducible; moving to DONE.
<img width="623" alt="stage_cor issue" src="https://user-images.githubusercontent.com/25797778/33627838-c214224a-d9cc-11e7-9924-6bf8f5b85bfc.png">

El Capitan OS X 10.11.6

**Comment by saimatsumoto** [comment]
Reopening the issue; it is still reproducible.
<img width="1440" alt="screen shot 2017-12-06 at 11 37 52 am" src="https://user-images.githubusercontent.com/25797778/33677174-e683b424-da85-11e7-9ca4-0360a239b6a2.png">

OS/Browser: OS X 10.11.6 / Chrome v62.0.3202.94

**Comment by thescientist13** [comment]
Found this forum, seems like it's a known issue as far back as 2012
https://forums.aws.amazon.com/message.jspa?messageID=445325

A lot of the workarounds mention CORS configurations in S3, but [this guide](https://coderwall.com/p/ub8zug/serving-web-fonts-via-aws-s3-and-cloudfront) seems to touch upon something applicable to us
> **HTTP/HTTPS**
>
> In the S3 example we allowed requests to come from both HTTP and HTTPS. When a CDN enters > the picture it will cache the response from S3. Therefore, if you request the font with HTTPS any
> future CORS request from HTTP will sadly fail (and vice-versa).
> 
> Pick one and stick with it.

Which is actually an open issue we have
https://github.com/ProvidenceGeeks/website-frontend/issues/83

Also, a comment suggests a temp workaround as well
> If you set up the 'behavior' in cloudfront to forward the Origin header using the whitelist, cloudfront will cache separate copies for http and https, but both will work at the same time. (Still, if possible, stick to one to improve caching ;)

**Comment by thescientist13** [comment]
This should be fixed by the resolution of #130 🤞

**Comment by thescientist13** [comment]
now it's showing in production... must be some sort of caching issue still

**Comment by thescientist13** [comment]
fixed in production, didn't have `OPTIONS` enabled as an allowed HTTP method on the production distribution
<img width="628" alt="screen shot 2018-01-09 at 1 14 48 pm" src="https://user-images.githubusercontent.com/895923/34735915-25a82fa8-f53f-11e7-890b-d73f37874c23.png">
