### ISSUE TITLE
Consider adding the meetup group name to the tile provide context…

### ISSUE THREAD

**Issue by jon077** [ProvidenceGeeks/website-frontend#94]
## Type of Change
- [X] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
**Consider adding the meetup group name to the tile provide context…**
<img width="1377" alt="screen_shot_2017-11-29_at_10 28 37_pm" src="https://user-images.githubusercontent.com/895923/33412696-1ae76d12-d55b-11e7-8807-bc522095df4b.png">

**Comment by thescientist13** [comment]
Thanks for this @jon077 , I think this would be a good idea!

We're always open to contributions, so If you're interested in making the change please feel free to submit a PR!  If you have any questions on getting started, please feel free to reach out.

Thanks for checking out the site!  👋

**Comment by saimatsumoto** [comment]
- [x] TEST - Stage: Meetup group name is displayed for each events on events-list. 
<img src="https://user-images.githubusercontent.com/25797778/34062135-108def5c-e1b9-11e7-91c0-438ad36cc023.png" width="30%" height="30%">  <img src="https://user-images.githubusercontent.com/25797778/34062154-26be899e-e1b9-11e7-9b90-2bdb1c13ec4d.png" width="30%" height="30%">  
Test device/browser: Win10 Chrome v62.0.3202.94 
- [ ] TEST - Prod:
