### ISSUE TITLE
navigation component is too coupled to its implementation details

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#95]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary

Currently the `NavigationBar` Component is bound to its implementation details of having an `EventsList` component and a `BlogPostsLists` component.  
```javascript
  return (

    <div className="row navigation-bar">
      <div className="col-md-12">

        <Tabs id="navigation-bar-tabs d-flex">
          <Tab eventKey={1} title="Events" className="events-tab-content">
            <div className="events">
              <EventsList />
            </div>
          </Tab>

          <Tab eventKey={2} title="Blog Posts" className="blog-tab-content">
            <BlogPostsList/>
          </Tab>
        </Tabs>

      </div>

    </div>
  );
```

While the `NavigationBar` component might only ever be used in this one instance on the Home Page, there is a high likelihood that the content and ordering of tabs themselves could change over time and having classnames and tests of specific configurations creates needless change in terms of classname and unit tests.

For example, we might want to swap the order of **Upcoming Events** and **Latest Posts**.  I would expect only the home page to care if that changes (e.g. a failing unit test), but in our current implementation, that would be breaking directly in the `NavigationBar` component's tests, which seems too low level.  

And the more obvious case is if we need to use tabbed navigation elsewhere in the app, we would have to create a new component or else break the Home Page implementation, which would of course be no bueno.

So, instead, lets pass components (like `EventsList` and `BlogPostsList`) as generic _child_ components via `this.props.children` to the `NavigationBar` instead, and let it create the tabs dynamically instead.

**Comment by thescientist13** [comment]
As this was a technical task, there should be no change in expected behavior.  🤞

**Comment by saimatsumoto** [comment]
No change in expected behavior.
![stage_fe25_navigation](https://user-images.githubusercontent.com/25797778/33574056-d4d201bc-d905-11e7-9188-4e4387afa72f.gif)
