### ISSUE TITLE
create a reusable grid component for componentizing 

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#99]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary

Currently, both the `EventsList` and `BlogPostsList` components manage the visibility and loading of their respective lists of data.  This leads to duplicate logic and code, but also exposes our code coverage to more gaps (see #98 ).  

Creating a reusable and generic component would address all these issues.

**Comment by thescientist13** [comment]
Technical change that should have not made any changes in existing behavior

**Comment by saimatsumoto** [comment]
As per above comment, moving to DONE.
